version: 2
builds:
  - main: ./cmd/cosmos-proposals-checker.go
    env:
      - CGO_ENABLED=1
    goos:
      - linux
      - darwin
nfpms:
  - vendor: 🐹 Quokka Stake
    maintainer: Sergey <freak12techno@gmail.com>
    formats:
      - deb
      - rpm
checksum:
  name_template: 'checksums.txt'
snapshot:
  version_template: "{{ .Tag }}"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
